In [2]:
import numpy as np

# Одновимірний масив
array_1d = np.arange(1, 11)
print(array_1d)
matrix_zeros = np.zeros((3, 3))
print(matrix_zeros)
matrix_random_int = np.random.randint(1, 11, (5, 5))
print(matrix_random_int)
matrix_random_float = np.random.random((4, 4))
print(matrix_random_float)
array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

print("Addition:", array1 + array2)
print("Subtraction:", array1 - array2)
print("Multiplication:", array1 * array2)
vector1 = np.random.random(7)
vector2 = np.random.random(7)

scalar_product = np.dot(vector1, vector2)
print(scalar_product)
matrix_a = np.random.randint(1, 11, (2, 2))
matrix_b = np.random.randint(1, 11, (2, 3))

product = np.dot(matrix_a, matrix_b)
print(product)
matrix_3x3 = np.random.randint(1, 11, (3, 3))
inverse_matrix = np.linalg.inv(matrix_3x3)
print(inverse_matrix)
matrix_4x4 = np.random.random((4, 4))
transposed_matrix = matrix_4x4.T
print(transposed_matrix)
matrix_3x4 = np.random.randint(1, 11, (3, 4))
vector_4 = np.random.randint(1, 11, 4)

result = np.dot(matrix_3x4, vector_4)
print(result)
matrix_a = np.random.randint(1, 11, (2, 2))
matrix_b = np.random.randint(1, 11, (2, 2))

elementwise_product = np.multiply(matrix_a, matrix_b)
print(elementwise_product)
matrix_5x5 = np.random.randint(1, 101, (5, 5))
matrix_sum = np.sum(matrix_5x5)
print(matrix_sum)
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(arr)
arr = np.arange(6)
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)
a = np.random.randint(1, 11, (2, 3))
b = np.random.randint(1, 11, (2, 3))

stacked = np.vstack((a, b))
print(stacked)
a = np.array([1, 2, 3])
output = np.hstack((np.repeat(a, 3), np.tile(a, 3)))
print(output)
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

common = np.intersect1d(a, b)
print(common)

[ 1  2  3  4  5  6  7  8  9 10]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 3  9  6  8  8]
 [ 2  6  2  4  5]
 [ 2  5  2  8  3]
 [ 6  9  9  1  9]
 [ 9  8  1  1 10]]
[[0.1341201  0.52536261 0.15407005 0.67043679]
 [0.76736956 0.8153961  0.29494762 0.81955341]
 [0.02935425 0.18277844 0.8871874  0.74452415]
 [0.88797691 0.50764434 0.47780882 0.30801979]]
Addition: [14 20 11 15 13]
Subtraction: [ 2  0 -9  1  1]
Multiplication: [ 48 100  10  56  42]
2.0368988711389937
[[ 50  62  58]
 [114  72  52]]
[[-0.34782609  0.23913043  0.08695652]
 [-0.65217391  0.76086957 -0.08695652]
 [ 1.47826087 -1.39130435  0.13043478]]
[[0.6500991  0.54232947 0.77811082 0.16918808]
 [0.55723988 0.15445905 0.68561716 0.23009874]
 [0.17056047 0.34585643 0.37979924 0.32331036]
 [0.82096396 0.00317117 0.43333975 0.92605588]]
[186 163  74]
[[ 5 42]
 [18 15]]
1179
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[[0 1 2]
 [3 4 5]]
[[ 8  5  7]
 [ 9  3  5]
 [10  2  8]
 [ 9  5  4]]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
[2 4]
